repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        require_serial: true
        exclude: ^(tests/.* |.*/logs/.*)$
        args: [
            "--rcfile=.pylintrc", # Usar arquivo de configuração .pylintrc
            "-rn",
            "-sn",
        ]
        exclude: ^(tests/.*)$
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--cov=src", "--cov-fail-under=80"]
